superlists/lists/urls.py
# from django.contrib import admin
# from django.urls import path

from django.conf.urls import url
from lists import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^new$',views.new_list,name='new_list'),
    url(r'^(\d+)/$',views.view_list, name='view_list'),
    url(r'^(\d+)/add_item$',views.add_item, name='add_item'),
]

superlists/superlists/urls.py
from django.conf.urls import url,include
from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^$',list_views.home_page,name='home'),
    url(r'^lists/',include(list_urls)),
]

superlists/lists/models.py
from django.db import models

class List(models.Model):
    pass

# Create your models here.
class Item(models.Model):
    # 没有长度限制的字符串类型字段
    text = models.TextField(default="")
    list = models.ForeignKey(List,on_delete=models.CASCADE, default=None)

superlists/lists/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from lists.models import Item,List
# Create your views here.
def home_page(request):
    # if request.method == "POST":
    #     return HttpResponse(request.POST['item_text'])
    # 第一个参数是请求，第二个参数要呈现的模板的名称。 
    # Django将在应用程序目录中自动搜索名为templates的文件夹。 
    # 然后，它会根据模板的内容为您构建一个HttpResponse。
    # if request.method == 'POST':
    #     Item.objects.create(text=request.POST['item_text'])
    #     return redirect('/lists/the-only-list-in-the-world/')
    return render(request,'home.html')
    # return HttpResponse("<html><title>To-Do lists</title></html>")


def view_list(request,list_id):
    list_ = List.objects.get(id=list_id)
    return render(request,'list.html',{'list':list_})


def new_list(request):
    list_ = List.objects.create()
    Item.objects.create(text=request.POST['item_text'],list=list_)
    return redirect(f'/lists/{list_.id}/')

def add_item(request,list_id):
    list_ = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST['item_text'],list=list_)
    return redirect(f'/lists/{list_.id}/')

superlists/lists/templates/base.html
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Comatible" content="IE=edge">
    <meta name='viewport' content="width=device-width,initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/base.css">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 jumbotron">
                <div class="text-center">
                    <h1>{% block header_text %}{% endblock %}</h1>
                    <form method="POST" action="{% block form_action %}{% endblock %}">
                        <input name="item_text" id="id_new_item" class="from-control input-lg" placeholder="Enter a to-do item" />
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block table %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

superlists/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}/lists/new{% endblock %}

superlists/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}/lists/{{list.id}}/add_item{% endblock %}

{% block table%}
    <table id="id_list_table" class="table" >
        {% for item in list.item_set.all %}
            <tr><td>{{forloop.counter}}: {{item.text}}</td></tr>
        {% endfor %}
    </table>

{% endblock %}